id: P009346
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN3407
  title: ལེགས་བཤད་ཉི་མའི་སྙིང་པོ།
  author: ''
  volumes:
    cd91afdd2f4c4a908dc8bc25554d8931:
      image_group_id: I3CN4388
      title: ''
      volume_number: 1
      total_pages: 420
      base_file: v001.txt
